language: node_js
node_js:
  - "5.10"

before_install:
  - "export CHROME_BIN=/usr/bin/google-chrome"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - npm install

script:
  - gulp build
  - gulp test
  - gulp coverage
  - gulp package
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls

notifications:
  slack: chartjs:pcfCZR6ugg5TEcaLtmIfQYuA

sudo: required
dist: trusty

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

deploy:
  provider: releases
  api_key:
    secure: E6JiZzA/Qy+UD1so/rVfqYnMhgU4m0cUsljxyrKIiYKlt/ZXo1XJabNkpEIYLvckrNx+g/4cmidNcuLfrnAZJtUg53qHLxyqMTXa9zAqmxxJ6aIpQpNK25FIEk9Xwm2XZdbI5rrm0ZciP5rcgg0X8/j5+RtnU3ZpTOCVkp0P73A=
  file:
  - "./dist/Chart.bundle.js"
  - "./dist/Chart.bundle.min.js"
  - "./dist/Chart.js"
  - "./dist/Chart.min.js"
  - "./dist/Chart.js.zip"
  skip_cleanup: true
  on:
    tags: true
